
MOVE_AHEAD = 'MoveAhead'
ROTATE_LEFT = 'RotateLeft'
ROTATE_RIGHT = 'RotateRight'
LOOK_UP = 'LookUp'
LOOK_DOWN = 'LookDown'
#DONE = 'Done'
LOCATE_TOMATO = 'LocateTomato'
LOCATE_BOWL = 'LocateBowl'
# LOCATE_BOTH = 'LocateBoth'


BASIC_ACTIONS = [MOVE_AHEAD, ROTATE_LEFT, ROTATE_RIGHT, LOOK_UP, LOOK_DOWN, LOCATE_TOMATO, LOCATE_BOWL]

GOAL_SUCCESS_REWARD = 5
STEP_PENALTY = -0.01
FAILED_ACTION_PENALTY = 0

LOCATE_REWARD = 2.5
WRONG_PENALTY = -1
PROGRESS_REWARD = 0.01